name: Build and Push Docker

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: echo "Building docker image"
      - name: Login to registry
        # run: echo "Login to docker registry"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - name: Set the tag
        run: |
          if [ -z "${{ inputs.tag }}"]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{ inputs.tag }}" >> $GITHUB_ENV
          fi
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push image
        run: echo "Pushing docker image to registry"